# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 252bdc9bd1e9976b1dffc5ecb57e3e211f643a9a05af5fc40c8235be71f56455ffadf1d6a4d77fe99b909b64ee01a0d39e2f38b31effbf2344f814ced3ce695f

test:
  secret_key_base: 98a56eae6ae4454ae471ed050d7b266c04d2eab7800d478edc3b23ebf836902d81d44d80f1d330e2e3ed82bd9424a52f7a1f73d33107343c15929608c569e3c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
